### PR TITLE
Restore compatibility with POSIX shell (Fixes #170)

### LINKED ISSUE #170: bashism in grub2-bls feature
Until this week, I was able to run perl-Bootloader with dash, a posix-sh like shell as /bin/sh. now not anymore. the reason is the `shellquote_raw` function (which got later moved into library with the same implementation) here:

https://github.com/openSUSE/perl-bootloader/commit/8229632e7ea768c00567fd68f5482e47555b80e9#diff-5040c10f2007cdf100863884e803f28326d282b568cd1046e2b77a0a6748d595R111-R117

variable substitutions are bash only. in order to make this compatible, it would have to use sed or the like:

```patch
-    arg=${1//\\/\\\\}
+    arg=$(echo "$1" | sed -e 's,\\/,\\\\,')
```

and the like

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by wfeldt** [comment]
update-bootloader does not support dash. I tried originally to keep it compatible but it's lacking features compared to ash, ksh, and bash. You'd have to keep using tmp files explicitly in a number of places, for example. And parameter expansions are more limited in dash as well.

As the point originally was to have non-gpl-3 alternatives, ash and ksh should suffice as choices. I think.

**Comment by wfeldt** [comment]
It's not just the places you noticed where it's dash-incompatible.

**Comment by dirkmueller** [comment]
so it works with dash with these changes. happy to patch further changes if possible. perl-bootloader/update-bootloader has been working with dash for the last decade until very recently, so I'd like to restore compatibility, if feasible.

**Comment by wfeldt** [comment]
I'd rather go with https://github.com/openSUSE/perl-bootloader/pull/181.

**Pull request closed without merging**
