### PR TITLE
Add initial implementation of uboot/config script

### PR DESCRIPTION
**Pull request by matwey**

### CODE REVIEW

**Comment by ancorgs** [comment]
And don't forget perl-bootloader is in the process of being dropped http://lists.opensuse.org/opensuse-factory/2015-11/msg00718.html

**Comment by jreidinger** [comment]
@ancorgs actually this pr is adapted for new p-bl. New p-bl only job is update config after kernel upgrade ( so for grub2 only grub2-mkconfig ). It should be in shell only and be trivial enough.

**Comment by arvidjaar** [comment]
> New p-bl only job is update config after kernel upgrade ( so for grub2 only grub2-mkconfig ).

Redundancy for Linux MD installation is completely implemented by pbl (it runs grub-install multiple times for each device). Also so far I could advice users to run "perl-bootloader --reinit" to ensure bootloader is installed according to YaST configuration. Do you really intend to remove this functionality?

**Comment by jreidinger** [comment]
@arvidjaar yes, as I hope yast2-bootloader can do such rewrite if needed. I think it make to do such think in yast2-bootloader. Another option is to create something like we had for grub1 which write shell script that record what yast2 did itself ( so set of grub-install calls, maybe also with generic_mbr install and marking active flag )

**Comment by matwey** [comment]
@afaerber
I've adopted kernel search for different architectures. Now, I've checked that the script creates bootable config for me on u-boot 2016.01-rc1.

**Pull request merged**
