### PR TITLE
git log

### PR DESCRIPTION
**Pull request by cwh42**
fix quoting issues (bsc#831791)

### CODE REVIEW

**Comment by wfeldt** [comment]
Shouldn't the '!' also be quoted (and 'qquote' called with ':shell')?

**Comment by wfeldt** [comment]
At least the grub2 manual says:

> The file /etc/default/grub controls the operation of grub-mkconfig. It is sourced by a shell script, and so must be valid POSIX shell input; normally, it will just be a sequence of ‘KEY=value’ lines, but if the value contains spaces or other special characters then it must be quoted.

Not sure how accurate the docs are, though.

**Comment by arvidjaar** [comment]
On Mon, Apr 27, 2015 at 3:12 PM, Steffen Winterfeldt <
notifications@github.com> wrote:

> At least the grub2 manual says:
>
> The file /etc/default/grub controls the operation of grub-mkconfig. It is
> sourced by a shell script, and so must be valid POSIX shell input;
> normally, it will just be a sequence of ‘KEY=value’ lines, but if the value
> contains spaces or other special characters then it must be quoted.
>
> Not sure how accurate the docs are, though.
>

This file is sourced by shell and so must be valid shell script.

**Comment by cwh42** [comment]
I added this kernel param for testing: acpi_osi="!Windows 2012" using yast/pbl
Case 1: Do not escape '!': Works fine, param ends up in /boot/grub2/grub.cfg this way: acpi_osi="!Windows 2012"
Case 2: Do escape '!' -> '\!': Works fine, param ends up in /boot/grub2/grub.cfg: acpi_osi="!Windows 2012"
Don't ask me why, but is simply works even without escaping.

**Comment by cwh42** [comment]
However: It definitely would make sense to also escape $s.

**Comment by arvidjaar** [comment]
On Mon, Apr 27, 2015 at 3:47 PM, Christopher Hofmann <
notifications@github.com> wrote:

> I added this kernel param for testing: acpi_osi="!Windows 2012" using
> yast/pbl
> Case 1: Do not escape '!': Works fine, param ends up in
> /boot/grub2/grub.cfg this way: acpi_osi="!Windows 2012"
> Case 2: Do escape '!' -> '!': Works fine, param ends up in
> /boot/grub2/grub.cfg: acpi_osi="!Windows 2012"
> Don't ask me why, but is simply works even without escaping.
>
"!" is special only in interactive bash unless I'm mistaken. grub-mkconfig
is called with #!/bin/sh and is non-interactive.

**Comment by wfeldt** [comment]
Ok, but this still leaves at least '$' to quote.

**Comment by wfeldt** [comment]
And '`' (backtick).

And possibly things like newline resp. chars below 0x20 in general.

**Comment by arvidjaar** [comment]
On Mon, Apr 27, 2015 at 4:11 PM, Steffen Winterfeldt <
notifications@github.com> wrote:

> And '`' (backtick).
>

While not encouraged,

GRUB_DISTRIBUTOR=`grep Some-String /etc/distro-release`

is valid and e.g. Ubuntu is actually using it. It allowed it to put correct
version indication matching running system without editing this file. So
quoting such things could actually cause problems for some users.

**Comment by wfeldt** [comment]
That's true. But you are talking about using different quotes altogether. That's afaik not at all supported in the yast frontend. If you encounter this, I'm sure crazy things will happen.

The sanest thing here might be to route backticks at the string's start and end through to yast
turning the entry into "`command foo bar`" which is still ok from the shell side.

**Comment by wfeldt** [comment]
should have been "\`command foo bar\`"

**Comment by jreidinger** [comment]
we actually plan to use backticks for distributor like @arvidjaar write, so pbl should pass it somehow.

**Comment by wfeldt** [comment]
So maybe a pair of backticks at start and end could be treated specially and end up without surrounding double quotes.

**Comment by jreidinger** [comment]
@wfeldt sounds good

**Comment by cwh42** [comment]
Quoting $ of course was easy; The backtick story follows soon.

**Comment by cwh42** [comment]
Things to think about:
Should option "always" maybe even quote backticked strings?
Already escaped quotes will also be backslashed, which actually unescapes them.

**Comment by cwh42** [comment]
I fixed the remaining issues, e.g. to not forget to unescape on reading and cleaned up this pull request.
Now it should be ready.

**Comment by wfeldt** [comment]
let's go for it

**Pull request merged**
