### PR TITLE
Bnc 899921

### PR DESCRIPTION
**Pull request by wfeldt**

### CODE REVIEW

**Comment by jreidinger** [comment]
LGTM

**Comment by wfeldt** [comment]
Thanks! But it's actually not finished yet. I'll add some tests. :-)

**Comment by wfeldt** [comment]
The reason for all this is that YAML::XS insists on passing utf8 encoded strings (not just binary data).
So we must do some tricks to pass data back and forth unchanged as best as we can. Else a single non-utf8 char somewhere in a file could alter the whole file unexpectedly.

**Comment by jreidinger** [comment]
just why tests are not written using Test:Simple in perl as in other tests? otherwise it looks good.

**Comment by wfeldt** [comment]
We need to test the yaml interface, not perl.

**Comment by jreidinger** [comment]
ok, so LGTM

**Pull request merged**
